### PR TITLE
Dealer score fixes

### PR DESCRIPTION
**Pull request by gabesullice**
Hi Mike,

So, I would see if you can go through these commits one by one to see the changes in more digestible hunks. It was certainly not over your head, mainly just a couple easy gotchas.

Primarily, you were binding to the hit and stay buttons outside of the document.ready closure. I put some more about that in the commit message.

After that, in the 'Fix dealer scoring' commit, it was just a matter of forgetting a double quote and using the wrong id, dealerCount vs. dealerScore, I believe.

The other changes in this PR are small things. The first is ignoring the .idea directory. It just muddles the commit history so it was hard for me to get an idea of what you were doing. Those configuration are also personal preference and don't really need to be committed.

The other two things were cleaning up some bad code that I had. The initial deal makes more sense being in the game constructor, and I biffed the dealer inheritance piece. I was overwriting all the methods inherited from the Player object on accident, so that one I fixed the code to display the card counts, I was getting an error about dealer.pointCount() not being defined.

Let me know if you need any more clarification on any of that.

Best,

Gabe

### CODE REVIEW

**Comment by gabesullice** [comment]
I just realized that there's a good chance I didn't actually answer your question by just submitting code. Code doesn't necessarily speak for itself and I likely didn't even fully take the time to appreciate what you were asking.

Please don't hesitate to expand on what you were trying to do/what you were having an issue with and I'll do my best to answer in English ;)

**Comment by mrmikemcguire** [comment]
OK, thanks.  I'll try to take this apart a little later today...:)

**Comment by mrmikemcguire** [comment]
@gabesullice 
_The first is ignoring the .idea directory. It just muddles the commit history so it was hard for me to get an idea of what you were doing. Those configuration are also personal preference and don't really need to be committed._

I had asked you about this earlier... if it should be listed in .gitignore.  Maybe I misunderstood, but I thought you said that's not how it's done.  Is there another way to ignore that directory?

Also, why are four aces being displayed?  I see that you added startingCards to the Game options.  Are these the dealer and player cards together and did they go out before shuffling?

**Comment by gabesullice** [comment]
Yeah, I think there was a miscommunication. You asked about ignoring workspace.xml and honestly, I had never seen that particular file before (now I realize it's <em>inside</em> the .idea directory) and I assumed it was just a holdover from opening whole directories containing multiple projects vs. opening just the project directory.

I linked to my standard [.gitignore file](http://hastebin.com/yodosadeki.ini) which ignores the whole .idea directory. I will typically drop that file into most repos as I start them. It will also ignore a lot of other little things that tend to find their way into a repo that really shouldn't be there. Sorry for the confusion on that one.

Yes, it looks like that's from the initial deal. They just appeared after I fixed the errors that were coming up so I assumed that it was your intent for them to be there.

**Pull request merged**
